CREATE DATABASE OPTUS;
GO

USE OPTUS;
GO

CREATE TABLE USUARIO(
	idUsuario SMALLINT PRIMARY KEY IDENTITY(1,1),
	nomeUsuario VARCHAR(15),
	email VARCHAR(30),
	senha VARCHAR(30),
	admAccess BIT
);
GO

CREATE TABLE EMPRESA(
	idEmpresa SMALLINT PRIMARY KEY IDENTITY(1,1),
	idArtista SMALLINT FOREIGN KEY REFERENCES ARTISTA(idArtista),
	idUsuario SMALLINT FOREIGN KEY REFERENCES USUARIO(idUsuario)
);
GO

CREATE TABLE ARTISTA(
	idArtista SMALLINT PRIMARY KEY IDENTITY(1,1),
	idAlbumEstilo SMALLINT FOREIGN KEY REFERENCES ALBUMESTILO(idAlbumEstilo),
	nomeArtista VARCHAR(15),
	idadeArtista TINYINT
);
GO

CREATE TABLE ALBUM(
	idAlbum SMALLINT PRIMARY KEY IDENTITY(1,1),
	nomeMusica VARCHAR(30),
	qtdMusicas TINYINT
);
GO

CREATE TABLE ALBUMESTILO(
	idAlbumEstilo SMALLINT PRIMARY KEY IDENTITY(1,1),
	idEstilo SMALLINT FOREIGN KEY REFERENCES ESTILO(idEstilo),
	idAlbum SMALLINT FOREIGN KEY REFERENCES ALBUM(idAlbum),
	visualizacoes INT 
);
GO

CREATE TABLE ESTILO(
	idEstilo SMALLINT PRIMARY KEY IDENTITY(1,1),
	nomeEstilo VARCHAR(20)
);
GO