CREATE DATABASE PCLINICS;
GO

USE PCLINICS;
GO

CREATE TABLE CLINICA(
	idClinica SMALLINT PRIMARY KEY IDENTITY(1,1),
	endereço VARCHAR(40) NOT NULL
);
GO

CREATE TABLE VETERINARIO(
	idVeterinario SMALLINT PRIMARY KEY IDENTITY(1,1),
	idClinica SMALLINT FOREIGN KEY REFERENCES CLINICA(idClinica),
	nomeVeterinario VARCHAR(15) NOT NULL
);
GO

CREATE TABLE PET(
	idPet SMALLINT PRIMARY KEY IDENTITY(1,1),
	nomePet VARCHAR(15)
);
GO

CREATE TABLE CONSULTA(
	idConsulta SMALLINT PRIMARY KEY IDENTITY(1,1),
	idVeterinario SMALLINT FOREIGN KEY REFERENCES VETERINARIO(idVeterinario),
	idPet SMALLINT FOREIGN KEY REFERENCES PET(idPet),
	dataConsulta VARCHAR(8)
);
GO

CREATE TABLE DONO(
	idDono SMALLINT PRIMARY KEY IDENTITY(1,1),
	idPet SMALLINT FOREIGN KEY REFERENCES PET(idPet),
	nomeDono VARCHAR(15)
);
GO

CREATE TABLE RACA(
	idRaca SMALLINT PRIMARY KEY IDENTITY(1,1),
	idPet SMALLINT FOREIGN KEY REFERENCES PET(idPet),
	nomeRaca VARCHAR(15)
);
GO

CREATE TABLE TIPOPET(
	idTipo SMALLINT PRIMARY KEY IDENTITY(1,1),
	idRaca SMALLINT FOREIGN KEY REFERENCES RACA(idRaca),
	tipoPet VARCHAR(15)
);
GO