CREATE DATABASE M_Rental;
GO

USE M_Rental;
GO

CREATE TABLE EMPRESA(
	idEmpresa SMALLINT PRIMARY KEY IDENTITY(1,1),
	nomeEmpresa VARCHAR(40) NOT NULL
);
GO

CREATE TABLE VEICULO(
	idVeiculo SMALLINT PRIMARY KEY IDENTITY(1,1),
	idModelo SMALLINT FOREIGN KEY REFERENCES MODELO(idModelo),
	idEmpresa SMALLINT FOREIGN KEY REFERENCES EMPRESA(idEmpresa),
	placa CHAR(7) NOT NULL
);
GO

CREATE TABLE ALUGUEL(
	idAluguel SMALLINT PRIMARY KEY IDENTITY(1,1),
	idVeiculo SMALLINT FOREIGN KEY REFERENCES VEICULO(idVeiculo),
	idCliente SMALLINT FOREIGN KEY REFERENCES CLIENTE(idCliente),
	dataAluguel CHAR(8) NOT NULL
);
GO

CREATE TABLE CLIENTE(
	idCliente SMALLINT PRIMARY KEY IDENTITY(1,1),
	nomeCliente VARCHAR(30) NOT NULL,
	sobrenomeCliente VARCHAR(50) NOT NULL,
	dataNascimento DATE NOT NULL
);
GO

CREATE TABLE MODELO(
	idModelo SMALLINT PRIMARY KEY IDENTITY(1,1),
	idMarca SMALLINT FOREIGN KEY REFERENCES MARCA(idMarca),
	nomeModelo VARCHAR(15) NOT NULL,
	anoModelo DATE NOT NULL
);
GO

CREATE TABLE MARCA(
	idMarca SMALLINT PRIMARY KEY IDENTITY(1,1),
	nomeMarca VARCHAR(20) NOT NULL
);
GO